apiVersion: v1
kind: Pod
metadata:
  name: redispod
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: redisdb-pvc
  containers:
    - name: task-pv-container
      image: redis
      ports:
        - containerPort: 6379
          name: "redis"
      volumeMounts:
        - mountPath: "/data"
          name: task-pv-storage


