apiVersion: v1
kind: Service
metadata:
  name: round-robin80
spec:
  selector:
    app: kubeserve
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 80
  type: NodePort

