# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestItalyvisaslot():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_italyvisaslot(self):
    self.driver.get("https://visa.vfsglobal.com/gbr/en/ita/login")
    self.driver.set_window_size(1900, 1020)
    self.driver.find_element(By.ID, "mat-input-0").click()
    self.driver.find_element(By.ID, "mat-input-0").send_keys("kaizhang@hotmail.com")
    self.driver.find_element(By.ID, "mat-input-1").send_keys("Maya4pro!")
    element = self.driver.find_element(By.CSS_SELECTOR, ".mat-button-wrapper")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".mat-button-wrapper").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".d-none > .mat-button-wrapper")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".d-none > .mat-button-wrapper").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".ngx-overlay")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.ID, "mat-select-value-1")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.CSS_SELECTOR, ".d-flex > div").click()
    self.driver.find_element(By.ID, "mat-select-value-1").click()
    self.driver.find_element(By.CSS_SELECTOR, "#mat-option-1 > .mat-option-text").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ngx-overlay").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".ngx-overlay")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.ID, "mat-select-value-5")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.CSS_SELECTOR, ".d-flex > div").click()
    self.driver.find_element(By.ID, "mat-select-value-5").click()
    self.driver.find_element(By.CSS_SELECTOR, "#mat-option-3 > .mat-option-text").click()
    self.driver.find_element(By.CSS_SELECTOR, ".alert").click()
    self.driver.find_element(By.CSS_SELECTOR, ".alert").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".alert")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
  
