version: '2'
services:
  nginx:
    restart: always
    image: nginx:latest
    ports:
    - "8080:80"
    volumes:
    - ./default.conf:/etc/nginx/conf.d/default.conf
    - /home/kaizhang/kaizha:/usr/share/nginx/html/logfiles/

  streamlit:
    restart: always
    image: streamlit:helloworld3
    # ports:
    # - "8080:8501"
