apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: fruit-service
  name: fruit-service
spec:
  replicas: 1
  selector:
    matchLabels:
      run: fruit-service
  strategy: {}
  template:
    metadata:
      labels:
        run: fruit-service
    spec:
      containers:
      - image: linuxacademycontent/legacy-fruit-service:1
        name: fruit-service
        ports:
        - containerPort: 80
      - image: haproxy:1.7 
        name: haproxy
        volumeMounts:
        - name: config-volume
          mountPath: /usr/local/etc/haproxy/
      volumes:
      - name: config-volume
        configMap:
          name: ckad-ex-multi-containers-pod

