apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: nginx1
  labels:
    name: nginx1
spec:
  volumes:
  - name: html
    # emptyDir: {}
    hostPath:
      path: /mnt 
      type: Directory

  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
    ports:
    - containerPort: 80

  - name: filecontainer
    image: debian
    volumeMounts:
    - name: html
      mountPath: /html
    command: ["/bin/sh", "-c"]
#    env:
#    - name: hweg
#      valueFrom:
#        configMapKeyRef:
#          name: hello-world-map
#          key: first
    envFrom:
    - configMapRef:
        name: hello-world-map
    args:
        - while true; do
          date >> /html/index.html;
          echo "Verison 1.1" >> /html/index.html;
          echo $(first) $(second) >> /html/index.html;
          sleep 60;
          done


