apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 1
  template:
    metadata:
    spec:
      containers:
      - name: main
        image: tutum/curl
        command: ["sleep", "9999999"]
      - name: proxy
        image: linuxacademycontent/kubectl-proxy
