apiVersion: v1
kind: Service
metadata:
  name: round-robin
spec:
  selector:
    app1: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
  type: NodePort

