## generated by antigravity claude sonnet 4.5 thinking model

import streamlit as st
import pandas as pd
import numpy as np
import requests
from datetime import datetime
import plotly.graph_objects as go

# Yahoo Finance Data Fetch Function
def yahoo_dataV8(stock, start_date, end_date, interval='1d'):
    """
    Fetch historical stock data from Yahoo Finance API
    """
    if interval not in ["1m", "2m", "5m", "15m", "30m", "1h", "1d", "5d", "1wk", "1mo"]:
        raise ValueError("Invalid Parameter for YahooV8 interval!")
    
    header = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9'}
    start_epoch = int(datetime.strptime(start_date, '%Y-%m-%d').timestamp())
    end_epoch = int(datetime.strptime(end_date, '%Y-%m-%d').timestamp())
    baseurl = "https://query1.finance.yahoo.com/v8/finance/chart/" + stock
    url = f"{baseurl}?period1={start_epoch}&period2={end_epoch}&interval={interval}&events=history"
    
    try:
        response = requests.get(url, headers=header)
        data = response.json()
        ohlc_json = data['chart']['result'][0]['indicators']['quote'][0]
        dates = data['chart']['result'][0]['timestamp']
        ohlc_json['date'] = pd.to_datetime(dates, unit='s')
        df = pd.DataFrame(ohlc_json)
        
        # Capitalize column names
        df.columns = [col.capitalize() for col in df.columns]
        
        # Set index based on interval
        if interval == '1d':
            df.index = df['Date'].dt.date
        else:
            df.index = df['Date']
        
        df = df.drop(columns=['Date'])
        
        return df
    except Exception as e:
        st.error(f"Error fetching data: {e}")
        return None

# MFI Calculation
def calculate_mfi(df, period=14):
    """Calculate Money Flow Index"""
    df = df.copy()
    
    # Calculate typical price
    df['typical_price'] = (df['High'] + df['Low'] + df['Close']) / 3
    
    # Calculate money flow
    df['money_flow'] = df['typical_price'] * df['Volume']
    
    # Calculate positive and negative money flow
    df['price_diff'] = df['typical_price'].diff()
    df['p_flow'] = np.where(df['price_diff'] > 0, df['money_flow'], 0)
    df['n_flow'] = np.where(df['price_diff'] < 0, df['money_flow'], 0)
    
    # Calculate MFI
    p_mf = df['p_flow'].rolling(window=period).sum()
    n_mf = df['n_flow'].rolling(window=period).sum()
    mf_ratio = p_mf / n_mf
    mfi = 100 - (100 / (1 + mf_ratio))
    
    return mfi

# RSI Calculation
def calculate_rsi(df, period=14):
    """Calculate Relative Strength Index"""
    df = df.copy()
    
    # Calculate price changes
    delta = df['Close'].diff()
    
    # Separate gains and losses
    gain = delta.where(delta > 0, 0)
    loss = -delta.where(delta < 0, 0)
    
    # Calculate average gain and loss
    avg_gain = gain.rolling(window=period).mean()
    avg_loss = loss.rolling(window=period).mean()
    
    # Calculate RS and RSI
    rs = avg_gain / avg_loss
    rsi = 100 - (100 / (1 + rs))
    
    return rsi

# Bollinger Bands Calculation
def calculate_bollinger_bands(df, period=20, num_std=2):
    """Calculate Bollinger Bands"""
    df = df.copy()
    
    # Calculate SMA
    sma = df['Close'].rolling(window=period).mean()
    
    # Calculate standard deviation
    std = df['Close'].rolling(window=period).std()
    
    # Calculate upper and lower bands
    upper_band = sma + (std * num_std)
    lower_band = sma - (std * num_std)
    
    return sma, upper_band, lower_band

# Get MFI Buy/Sell Signals
def get_mfi_signals(mfi, high=80, low=25):
    """Generate buy/sell signals based on MFI"""
    buy_signal = []
    sell_signal = []
    
    for i in range(len(mfi)):
        if mfi.iloc[i] > high:
            buy_signal.append(np.nan)
            sell_signal.append(i)
        elif mfi.iloc[i] < low:
            buy_signal.append(i)
            sell_signal.append(np.nan)
        else:
            buy_signal.append(np.nan)
            sell_signal.append(np.nan)
    
    return buy_signal, sell_signal

# Streamlit App
def main():
    st.title("📈 Stock Technical Analysis Dashboard")
    st.write("Analyze stocks using MFI, RSI, and Bollinger Bands")
    
    # Sidebar for inputs
    st.sidebar.header("Input Parameters")
    
    ticker = st.sidebar.text_input("Ticker Symbol", value="MSFT").upper()
    start_date = st.sidebar.date_input("Start Date", value=pd.to_datetime("2020-01-01"))
    end_date = st.sidebar.date_input("End Date", value=pd.to_datetime("2020-10-27"))
    interval = st.sidebar.selectbox("Interval", 
                                    options=['1d', '1h', '30m', '15m', '5m', '2m', '1m', '5d', '1wk', '1mo'],
                                    index=0)
    
    # Fetch data button
    if st.sidebar.button("Fetch Data & Analyze"):
        with st.spinner("Fetching data..."):
            # Convert dates to strings
            start_str = start_date.strftime('%Y-%m-%d')
            end_str = end_date.strftime('%Y-%m-%d')
            
            # Fetch data
            df = yahoo_dataV8(ticker, start_str, end_str, interval)
            
            if df is not None and not df.empty:
                st.success(f"Successfully fetched {len(df)} data points for {ticker}")
                
                # Display raw data
                st.subheader("📊 Raw Data Preview")
                st.dataframe(df.head(10))
                
                # Calculate indicators
                mfi_period = 14
                mfi = calculate_mfi(df, mfi_period)
                rsi = calculate_rsi(df)
                sma, upper_band, lower_band = calculate_bollinger_bands(df)
                
                # Create full dataframe with indicators
                full_df = df[mfi_period:].copy()
                full_df['MFI'] = mfi[mfi_period:]
                full_df['RSI'] = rsi[mfi_period:]
                full_df['SMA'] = sma[mfi_period:]
                full_df['Upper_Band'] = upper_band[mfi_period:]
                full_df['Lower_Band'] = lower_band[mfi_period:]
                
                # Get MFI signals
                buy_signals, sell_signals = get_mfi_signals(full_df['MFI'])
                
                # Chart 1: Price with MFI Signals
                st.subheader("💹 Price Chart with MFI Buy/Sell Signals")
                fig1 = go.Figure()
                fig1.add_trace(go.Scatter(x=full_df.index, y=full_df['Close'], name='Close Price', 
                                        line=dict(color='blue', width=2), opacity=0.5))
                
                # Plot buy signals
                buy_idx = [i for i, val in enumerate(buy_signals) if not np.isnan(val)]
                if buy_idx:
                    fig1.add_trace(go.Scatter(
                        x=[full_df.index[i] for i in buy_idx], 
                        y=[full_df['Close'].iloc[i] for i in buy_idx],
                        mode='markers',
                        name='Buy Signal (MFI < 25)',
                        marker=dict(color='green', symbol='triangle-up', size=12, line=dict(width=1, color='darkgreen'))
                    ))
                
                # Plot sell signals
                sell_idx = [i for i, val in enumerate(sell_signals) if not np.isnan(val)]
                if sell_idx:
                    fig1.add_trace(go.Scatter(
                        x=[full_df.index[i] for i in sell_idx], 
                        y=[full_df['Close'].iloc[i] for i in sell_idx],
                        mode='markers',
                        name='Sell Signal (MFI > 80)',
                        marker=dict(color='red', symbol='triangle-down', size=12, line=dict(width=1, color='darkred'))
                    ))
                
                fig1.update_layout(
                    title=f'{ticker} - Close Price with MFI Signals',
                    xaxis_title='Date',
                    yaxis_title='Price (USD)',
                    hovermode="x unified",
                    legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01)
                )
                st.plotly_chart(fig1, use_container_width=True)
                
                # Chart 2: Bollinger Bands
                st.subheader("📊 Bollinger Bands")
                fig2 = go.Figure()
                
                # Add Upper Band first
                fig2.add_trace(go.Scatter(x=full_df.index, y=full_df['Upper_Band'], name='Upper Band',
                                        line=dict(color='rgba(255, 0, 0, 0.5)', width=1, dash='dot')))
                
                # Add Lower Band with fill to Upper Band
                fig2.add_trace(go.Scatter(x=full_df.index, y=full_df['Lower_Band'], name='Lower Band',
                                        line=dict(color='rgba(0, 255, 0, 0.5)', width=1, dash='dot'),
                                        fill='tonexty', fillcolor='rgba(128, 128, 128, 0.1)'))
                
                fig2.add_trace(go.Scatter(x=full_df.index, y=full_df['Close'], name='Close Price',
                                        line=dict(color='blue', width=2)))
                fig2.add_trace(go.Scatter(x=full_df.index, y=full_df['SMA'], name='SMA (20)',
                                        line=dict(color='orange', width=1.5, dash='dash')))
                
                fig2.update_layout(
                    title=f'{ticker} - Bollinger Bands',
                    xaxis_title='Date',
                    yaxis_title='Price (USD)',
                    hovermode="x unified",
                    legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01)
                )
                st.plotly_chart(fig2, use_container_width=True)
                
                # Chart 3: RSI
                st.subheader("📈 Relative Strength Index (RSI)")
                fig3 = go.Figure()
                fig3.add_trace(go.Scatter(x=full_df.index, y=full_df['RSI'], name='RSI',
                                        line=dict(color='purple', width=2)))
                
                # Overbought/Oversold lines
                fig3.add_hline(y=70, line_dash="dash", line_color="red", annotation_text="Overbought (70)")
                fig3.add_hline(y=30, line_dash="dash", line_color="green", annotation_text="Oversold (30)")
                
                # Add color bands background for 30-70 range? Or just simple approach for now. 
                # Plotly doesn't have a simple 'axhspan' like matplotlib equivalent for background without a trace.
                # Use shapes for background color if desired, but lines are usually sufficient.
                
                fig3.update_yaxes(range=[0, 100])
                fig3.update_layout(
                    title=f'{ticker} - RSI Indicator',
                    xaxis_title='Date',
                    yaxis_title='RSI',
                    hovermode="x unified"
                )
                st.plotly_chart(fig3, use_container_width=True)
                
                # Display indicator values
                st.subheader("📋 Technical Indicators Summary")
                col1, col2, col3 = st.columns(3)
                with col1:
                    st.metric("Latest MFI", f"{full_df['MFI'].iloc[-1]:.2f}")
                with col2:
                    st.metric("Latest RSI", f"{full_df['RSI'].iloc[-1]:.2f}")
                with col3:
                    st.metric("Latest Close", f"${full_df['Close'].iloc[-1]:.2f}")
                
                # Download data option
                st.subheader("💾 Download Data")
                csv = full_df.to_csv()
                st.download_button(
                    label="Download CSV",
                    data=csv,
                    file_name=f"{ticker}_technical_analysis.csv",
                    mime="text/csv"
                )
            else:
                st.error("Failed to fetch data. Please check the ticker symbol and date range.")

if __name__ == "__main__":
    main()
